# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\manualservice.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManualService(object):
    def setupUi(self, ManualService):
        ManualService.setObjectName("ManualService")
        ManualService.resize(350, 414)
        ManualService.setStyleSheet("")
        ManualService.setSizeGripEnabled(True)
        ManualService.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(ManualService)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.disconnect_button = QtWidgets.QPushButton(ManualService)
        self.disconnect_button.setObjectName("disconnect_button")
        self.horizontalLayout_2.addWidget(self.disconnect_button)
        self.waiting_button = QtWidgets.QPushButton(ManualService)
        self.waiting_button.setObjectName("waiting_button")
        self.horizontalLayout_2.addWidget(self.waiting_button)
        self.connect_button = QtWidgets.QPushButton(ManualService)
        self.connect_button.setObjectName("connect_button")
        self.horizontalLayout_2.addWidget(self.connect_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.message_box = QtWidgets.QTextEdit(ManualService)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_box.sizePolicy().hasHeightForWidth())
        self.message_box.setSizePolicy(sizePolicy)
        self.message_box.setMinimumSize(QtCore.QSize(0, 50))
        self.message_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.message_box.setObjectName("message_box")
        self.horizontalLayout_3.addWidget(self.message_box)
        self.message_button = QtWidgets.QPushButton(ManualService)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_button.sizePolicy().hasHeightForWidth())
        self.message_button.setSizePolicy(sizePolicy)
        self.message_button.setObjectName("message_button")
        self.horizontalLayout_3.addWidget(self.message_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.frame = QtWidgets.QFrame(ManualService)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ground_speed = QtWidgets.QDoubleSpinBox(self.frame)
        self.ground_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.ground_speed.setMinimum(-1000.0)
        self.ground_speed.setMaximum(1000.0)
        self.ground_speed.setObjectName("ground_speed")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ground_speed)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.rpm = QtWidgets.QDoubleSpinBox(self.frame)
        self.rpm.setAlignment(QtCore.Qt.AlignCenter)
        self.rpm.setMinimum(-1000.0)
        self.rpm.setMaximum(1000.0)
        self.rpm.setObjectName("rpm")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rpm)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.oil_pressure = QtWidgets.QDoubleSpinBox(self.frame)
        self.oil_pressure.setAlignment(QtCore.Qt.AlignCenter)
        self.oil_pressure.setMinimum(-1000.0)
        self.oil_pressure.setMaximum(1000.0)
        self.oil_pressure.setObjectName("oil_pressure")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.oil_pressure)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.fuel_used = QtWidgets.QDoubleSpinBox(self.frame)
        self.fuel_used.setAlignment(QtCore.Qt.AlignCenter)
        self.fuel_used.setMinimum(-1000.0)
        self.fuel_used.setMaximum(1000.0)
        self.fuel_used.setObjectName("fuel_used")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fuel_used)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.throttle = QtWidgets.QDoubleSpinBox(self.frame)
        self.throttle.setAlignment(QtCore.Qt.AlignCenter)
        self.throttle.setMinimum(-1000.0)
        self.throttle.setMaximum(1000.0)
        self.throttle.setObjectName("throttle")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.throttle)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.ignition_advance = QtWidgets.QDoubleSpinBox(self.frame)
        self.ignition_advance.setAlignment(QtCore.Qt.AlignCenter)
        self.ignition_advance.setMinimum(-1000.0)
        self.ignition_advance.setMaximum(1000.0)
        self.ignition_advance.setObjectName("ignition_advance")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ignition_advance)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.air_temperature = QtWidgets.QDoubleSpinBox(self.frame)
        self.air_temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.air_temperature.setMinimum(-1000.0)
        self.air_temperature.setMaximum(1000.0)
        self.air_temperature.setObjectName("air_temperature")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.air_temperature)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.engine_temperature = QtWidgets.QDoubleSpinBox(self.frame)
        self.engine_temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.engine_temperature.setMinimum(-1000.0)
        self.engine_temperature.setMaximum(1000.0)
        self.engine_temperature.setObjectName("engine_temperature")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.engine_temperature)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.battery = QtWidgets.QDoubleSpinBox(self.frame)
        self.battery.setAlignment(QtCore.Qt.AlignCenter)
        self.battery.setMinimum(-1000.0)
        self.battery.setMaximum(1000.0)
        self.battery.setObjectName("battery")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.battery)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lambda_1 = QtWidgets.QDoubleSpinBox(self.frame)
        self.lambda_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lambda_1.setMinimum(-1000.0)
        self.lambda_1.setMaximum(1000.0)
        self.lambda_1.setObjectName("lambda_1")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lambda_1)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.load_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_button.sizePolicy().hasHeightForWidth())
        self.load_button.setSizePolicy(sizePolicy)
        self.load_button.setObjectName("load_button")
        self.horizontalLayout_4.addWidget(self.load_button, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(ManualService)
        QtCore.QMetaObject.connectSlotsByName(ManualService)

    def retranslateUi(self, ManualService):
        _translate = QtCore.QCoreApplication.translate
        ManualService.setWindowTitle(_translate("ManualService", "Servicio de datos"))
        self.disconnect_button.setText(_translate("ManualService", "DESCONECTAR"))
        self.waiting_button.setText(_translate("ManualService", "EN ESPERA..."))
        self.connect_button.setText(_translate("ManualService", "CONECTAR"))
        self.message_button.setText(_translate("ManualService", "ACTUALIZAR"))
        self.label.setText(_translate("ManualService", "Ground Speed"))
        self.label_2.setText(_translate("ManualService", "RPM"))
        self.label_3.setText(_translate("ManualService", "Oil Pressure"))
        self.label_4.setText(_translate("ManualService", "Fuel Used"))
        self.label_5.setText(_translate("ManualService", "Throttle"))
        self.label_6.setText(_translate("ManualService", "Ignition Advance"))
        self.label_7.setText(_translate("ManualService", "Air Temperature"))
        self.label_8.setText(_translate("ManualService", "Engine Temperature"))
        self.label_9.setText(_translate("ManualService", "Battery"))
        self.label_10.setText(_translate("ManualService", "Lambda"))
        self.load_button.setText(_translate("ManualService", "CARGAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManualService = QtWidgets.QDialog()
    ui = Ui_ManualService()
    ui.setupUi(ManualService)
    ManualService.show()
    sys.exit(app.exec_())
