# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\micconfig.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MicConfig(object):
    def setupUi(self, MicConfig):
        MicConfig.setObjectName("MicConfig")
        MicConfig.resize(317, 256)
        self.verticalLayout = QtWidgets.QVBoxLayout(MicConfig)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(50)
        self.gridLayout.setVerticalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.format = QtWidgets.QComboBox(MicConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format.sizePolicy().hasHeightForWidth())
        self.format.setSizePolicy(sizePolicy)
        self.format.setMinimumSize(QtCore.QSize(150, 0))
        self.format.setFrame(True)
        self.format.setObjectName("format")
        self.format.addItem("")
        self.format.addItem("")
        self.format.addItem("")
        self.format.addItem("")
        self.gridLayout.addWidget(self.format, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(MicConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(MicConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(MicConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.devices = QtWidgets.QComboBox(MicConfig)
        self.devices.setObjectName("devices")
        self.gridLayout.addWidget(self.devices, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(MicConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.sample_rate = QtWidgets.QLineEdit(MicConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_rate.sizePolicy().hasHeightForWidth())
        self.sample_rate.setSizePolicy(sizePolicy)
        self.sample_rate.setMinimumSize(QtCore.QSize(150, 0))
        self.sample_rate.setFrame(False)
        self.sample_rate.setObjectName("sample_rate")
        self.gridLayout.addWidget(self.sample_rate, 1, 1, 1, 1)
        self.channels = QtWidgets.QLineEdit(MicConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channels.sizePolicy().hasHeightForWidth())
        self.channels.setSizePolicy(sizePolicy)
        self.channels.setMinimumSize(QtCore.QSize(150, 0))
        self.channels.setFrame(False)
        self.channels.setObjectName("channels")
        self.gridLayout.addWidget(self.channels, 2, 1, 1, 1)
        self.frames_per_buffer = QtWidgets.QLineEdit(MicConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frames_per_buffer.sizePolicy().hasHeightForWidth())
        self.frames_per_buffer.setSizePolicy(sizePolicy)
        self.frames_per_buffer.setMinimumSize(QtCore.QSize(150, 0))
        self.frames_per_buffer.setFrame(False)
        self.frames_per_buffer.setObjectName("frames_per_buffer")
        self.gridLayout.addWidget(self.frames_per_buffer, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.apply = QtWidgets.QPushButton(MicConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply.sizePolicy().hasHeightForWidth())
        self.apply.setSizePolicy(sizePolicy)
        self.apply.setObjectName("apply")
        self.verticalLayout.addWidget(self.apply, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(MicConfig)
        QtCore.QMetaObject.connectSlotsByName(MicConfig)

    def retranslateUi(self, MicConfig):
        _translate = QtCore.QCoreApplication.translate
        MicConfig.setWindowTitle(_translate("MicConfig", "Form"))
        self.format.setItemText(0, _translate("MicConfig", "1 Byte"))
        self.format.setItemText(1, _translate("MicConfig", "2 Bytes"))
        self.format.setItemText(2, _translate("MicConfig", "3 Bytes"))
        self.format.setItemText(3, _translate("MicConfig", "4 Bytes"))
        self.label_4.setText(_translate("MicConfig", "TASA DE MUESTREO"))
        self.label_3.setText(_translate("MicConfig", "CANALES"))
        self.label.setText(_translate("MicConfig", "FRAMES POR BUFFER"))
        self.label_2.setText(_translate("MicConfig", "FORMATO"))
        self.sample_rate.setText(_translate("MicConfig", "48000"))
        self.channels.setText(_translate("MicConfig", "1"))
        self.frames_per_buffer.setText(_translate("MicConfig", "1024"))
        self.apply.setText(_translate("MicConfig", "Aplicar cambios"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MicConfig = QtWidgets.QWidget()
    ui = Ui_MicConfig()
    ui.setupUi(MicConfig)
    MicConfig.show()
    sys.exit(app.exec_())
