# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/panel.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(1557, 523)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Panel.sizePolicy().hasHeightForWidth())
        Panel.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Panel)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ground_speed_display = CircularGauge(Panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ground_speed_display.sizePolicy().hasHeightForWidth())
        self.ground_speed_display.setSizePolicy(sizePolicy)
        self.ground_speed_display.setMinimumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        self.ground_speed_display.setProperty("label_font", font)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(60)
        self.ground_speed_display.setProperty("value_font", font)
        self.ground_speed_display.setProperty("value", 125)
        self.ground_speed_display.setProperty("max_value", 250)
        brush = QtGui.QBrush(QtGui.QColor(77, 104, 112, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.ground_speed_display.setProperty("bar_background", brush)
        self.ground_speed_display.setObjectName("ground_speed_display")
        self.horizontalLayout.addWidget(self.ground_speed_display)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.gridWidget = QtWidgets.QWidget(Panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridWidget.sizePolicy().hasHeightForWidth())
        self.gridWidget.setSizePolicy(sizePolicy)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_6 = QtWidgets.QFrame(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("background: rgba(30, 98, 87, 10)")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(1)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.engine_temperature_display = IconData(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.engine_temperature_display.sizePolicy().hasHeightForWidth())
        self.engine_temperature_display.setSizePolicy(sizePolicy)
        self.engine_temperature_display.setProperty("value", 198)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.engine_temperature_display.setProperty("value_font", font)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.engine_temperature_display.setProperty("label_font", font)
        self.engine_temperature_display.setProperty("scale", 0.8)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/thermometer/assets/thermometer/Car_Engine_-_Dashboard_Lights_110-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.engine_temperature_display.setProperty("icon", icon)
        self.engine_temperature_display.setObjectName("engine_temperature_display")
        self.verticalLayout_7.addWidget(self.engine_temperature_display)
        self.gridLayout.addWidget(self.frame_6, 2, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background: rgba(30, 98, 87, 10)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.throttle_display = IconData(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.throttle_display.sizePolicy().hasHeightForWidth())
        self.throttle_display.setSizePolicy(sizePolicy)
        self.throttle_display.setProperty("value", 60)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.throttle_display.setProperty("value_font", font)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.throttle_display.setProperty("label_font", font)
        self.throttle_display.setProperty("scale", 0.8)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/throttle/assets/throttle/2303987-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.throttle_display.setProperty("icon", icon1)
        self.throttle_display.setObjectName("throttle_display")
        self.verticalLayout_2.addWidget(self.throttle_display)
        self.gridLayout.addWidget(self.frame_2, 3, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("background: rgba(30, 98, 87, 10)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.air_temperature_display = IconData(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.air_temperature_display.sizePolicy().hasHeightForWidth())
        self.air_temperature_display.setSizePolicy(sizePolicy)
        self.air_temperature_display.setProperty("value", 35)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.air_temperature_display.setProperty("value_font", font)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.air_temperature_display.setProperty("label_font", font)
        self.air_temperature_display.setProperty("scale", 0.8)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/thermometer/assets/thermometer/120779.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.air_temperature_display.setProperty("icon", icon2)
        self.air_temperature_display.setObjectName("air_temperature_display")
        self.verticalLayout_3.addWidget(self.air_temperature_display)
        self.gridLayout.addWidget(self.frame_3, 3, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("background: rgba(30, 98, 87, 10)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(1)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lambda_display = IconData(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lambda_display.sizePolicy().hasHeightForWidth())
        self.lambda_display.setSizePolicy(sizePolicy)
        self.lambda_display.setProperty("value", 12)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.lambda_display.setProperty("value_font", font)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.lambda_display.setProperty("label_font", font)
        self.lambda_display.setProperty("scale", 0.8)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/lambda/assets/lambda/lambda-97846_960_720.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lambda_display.setProperty("icon", icon3)
        self.lambda_display.setObjectName("lambda_display")
        self.verticalLayout_6.addWidget(self.lambda_display)
        self.gridLayout.addWidget(self.frame_5, 2, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background: rgba(30, 98, 87, 10)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.battery_display = IconData(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.battery_display.sizePolicy().hasHeightForWidth())
        self.battery_display.setSizePolicy(sizePolicy)
        self.battery_display.setProperty("value", 12)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.battery_display.setProperty("value_font", font)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.battery_display.setProperty("label_font", font)
        self.battery_display.setProperty("scale", 0.8)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/battery/assets/battery/car+battery+icon-1320184285905906096.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.battery_display.setProperty("icon", icon4)
        self.battery_display.setObjectName("battery_display")
        self.verticalLayout.addWidget(self.battery_display)
        self.gridLayout.addWidget(self.frame, 3, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("background: rgba(30, 98, 87, 10)")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(1)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.oil_pressure_display = IconData(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oil_pressure_display.sizePolicy().hasHeightForWidth())
        self.oil_pressure_display.setSizePolicy(sizePolicy)
        self.oil_pressure_display.setProperty("value", 2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.oil_pressure_display.setProperty("value_font", font)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.oil_pressure_display.setProperty("label_font", font)
        self.oil_pressure_display.setProperty("scale", 0.8)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/oil/assets/oil/17696-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.oil_pressure_display.setProperty("icon", icon5)
        self.oil_pressure_display.setObjectName("oil_pressure_display")
        self.verticalLayout_8.addWidget(self.oil_pressure_display)
        self.gridLayout.addWidget(self.frame_7, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("background: rgba(30, 98, 87, 10)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(1)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fuel_used_display = IconData(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fuel_used_display.sizePolicy().hasHeightForWidth())
        self.fuel_used_display.setSizePolicy(sizePolicy)
        self.fuel_used_display.setProperty("value", 9)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.fuel_used_display.setProperty("value_font", font)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.fuel_used_display.setProperty("label_font", font)
        self.fuel_used_display.setProperty("scale", 0.8)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/fuel/assets/fuel/fuel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fuel_used_display.setProperty("icon", icon6)
        self.fuel_used_display.setObjectName("fuel_used_display")
        self.verticalLayout_4.addWidget(self.fuel_used_display)
        self.gridLayout.addWidget(self.frame_4, 3, 3, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setStyleSheet("background: rgba(30, 98, 87, 10)")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_15.setLineWidth(1)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.ignition_advance_display = IconData(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ignition_advance_display.sizePolicy().hasHeightForWidth())
        self.ignition_advance_display.setSizePolicy(sizePolicy)
        self.ignition_advance_display.setProperty("value", 9)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.ignition_advance_display.setProperty("value_font", font)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.ignition_advance_display.setProperty("label_font", font)
        self.ignition_advance_display.setProperty("scale", 0.8)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ignition/assets/ignition/50425-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ignition_advance_display.setProperty("icon", icon7)
        self.ignition_advance_display.setObjectName("ignition_advance_display")
        self.verticalLayout_16.addWidget(self.ignition_advance_display)
        self.gridLayout.addWidget(self.frame_15, 2, 3, 1, 1)
        self.verticalLayout_5.addWidget(self.gridWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.rpm_display = CircularGauge(Panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rpm_display.sizePolicy().hasHeightForWidth())
        self.rpm_display.setSizePolicy(sizePolicy)
        self.rpm_display.setMinimumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        self.rpm_display.setProperty("label_font", font)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(60)
        self.rpm_display.setProperty("value_font", font)
        self.rpm_display.setProperty("value", 10000)
        self.rpm_display.setProperty("min_value", 0)
        self.rpm_display.setProperty("max_value", 20000)
        brush = QtGui.QBrush(QtGui.QColor(77, 104, 112, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.rpm_display.setProperty("bar_background", brush)
        self.rpm_display.setObjectName("rpm_display")
        self.horizontalLayout.addWidget(self.rpm_display)

        self.retranslateUi(Panel)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        _translate = QtCore.QCoreApplication.translate
        Panel.setWindowTitle(_translate("Panel", "Form"))
        self.ground_speed_display.setToolTip(_translate("Panel", "Click and drag here"))
        self.ground_speed_display.setWhatsThis(_translate("Panel", "Circular Gauge Widget.  "))
        self.ground_speed_display.setProperty("label", _translate("Panel", "KM/H"))
        self.engine_temperature_display.setToolTip(_translate("Panel", "Click and drag here"))
        self.engine_temperature_display.setWhatsThis(_translate("Panel", "Icon Data Widget.  "))
        self.engine_temperature_display.setProperty("label", _translate("Panel", "°C"))
        self.throttle_display.setToolTip(_translate("Panel", "Click and drag here"))
        self.throttle_display.setWhatsThis(_translate("Panel", "Icon Data Widget.  "))
        self.throttle_display.setProperty("label", _translate("Panel", "%"))
        self.air_temperature_display.setToolTip(_translate("Panel", "Click and drag here"))
        self.air_temperature_display.setWhatsThis(_translate("Panel", "Icon Data Widget.  "))
        self.air_temperature_display.setProperty("label", _translate("Panel", "°C"))
        self.lambda_display.setToolTip(_translate("Panel", "Click and drag here"))
        self.lambda_display.setWhatsThis(_translate("Panel", "Icon Data Widget.  "))
        self.lambda_display.setProperty("label", _translate("Panel", "V"))
        self.battery_display.setToolTip(_translate("Panel", "Click and drag here"))
        self.battery_display.setWhatsThis(_translate("Panel", "Icon Data Widget.  "))
        self.battery_display.setProperty("label", _translate("Panel", "V"))
        self.oil_pressure_display.setToolTip(_translate("Panel", "Click and drag here"))
        self.oil_pressure_display.setWhatsThis(_translate("Panel", "Icon Data Widget.  "))
        self.oil_pressure_display.setProperty("label", _translate("Panel", "kPa"))
        self.fuel_used_display.setToolTip(_translate("Panel", "Click and drag here"))
        self.fuel_used_display.setWhatsThis(_translate("Panel", "Icon Data Widget.  "))
        self.fuel_used_display.setProperty("label", _translate("Panel", "L"))
        self.ignition_advance_display.setToolTip(_translate("Panel", "Click and drag here"))
        self.ignition_advance_display.setWhatsThis(_translate("Panel", "Icon Data Widget.  "))
        self.ignition_advance_display.setProperty("label", _translate("Panel", "°"))
        self.rpm_display.setToolTip(_translate("Panel", "Click and drag here"))
        self.rpm_display.setWhatsThis(_translate("Panel", "Circular Gauge Widget.  "))
from src.widgets.gaugewidget import CircularGauge
from src.widgets.icondatawidget import IconData
from src.resources import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Panel = QtWidgets.QWidget()
    ui = Ui_Panel()
    ui.setupUi(Panel)
    Panel.show()
    sys.exit(app.exec_())
