# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\soundconfig.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SoundConfig(object):
    def setupUi(self, SoundConfig):
        SoundConfig.setObjectName("SoundConfig")
        SoundConfig.resize(317, 256)
        self.verticalLayout = QtWidgets.QVBoxLayout(SoundConfig)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(50)
        self.gridLayout.setVerticalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.format = QtWidgets.QComboBox(SoundConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format.sizePolicy().hasHeightForWidth())
        self.format.setSizePolicy(sizePolicy)
        self.format.setMinimumSize(QtCore.QSize(150, 0))
        self.format.setFrame(True)
        self.format.setObjectName("format")
        self.format.addItem("")
        self.format.addItem("")
        self.format.addItem("")
        self.format.addItem("")
        self.gridLayout.addWidget(self.format, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(SoundConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(SoundConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(SoundConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.devices = QtWidgets.QComboBox(SoundConfig)
        self.devices.setObjectName("devices")
        self.gridLayout.addWidget(self.devices, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(SoundConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.sample_rate = QtWidgets.QLineEdit(SoundConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_rate.sizePolicy().hasHeightForWidth())
        self.sample_rate.setSizePolicy(sizePolicy)
        self.sample_rate.setMinimumSize(QtCore.QSize(150, 0))
        self.sample_rate.setFrame(False)
        self.sample_rate.setObjectName("sample_rate")
        self.gridLayout.addWidget(self.sample_rate, 1, 1, 1, 1)
        self.channels = QtWidgets.QLineEdit(SoundConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channels.sizePolicy().hasHeightForWidth())
        self.channels.setSizePolicy(sizePolicy)
        self.channels.setMinimumSize(QtCore.QSize(150, 0))
        self.channels.setFrame(False)
        self.channels.setObjectName("channels")
        self.gridLayout.addWidget(self.channels, 2, 1, 1, 1)
        self.frames_per_buffer = QtWidgets.QLineEdit(SoundConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frames_per_buffer.sizePolicy().hasHeightForWidth())
        self.frames_per_buffer.setSizePolicy(sizePolicy)
        self.frames_per_buffer.setMinimumSize(QtCore.QSize(150, 0))
        self.frames_per_buffer.setFrame(False)
        self.frames_per_buffer.setObjectName("frames_per_buffer")
        self.gridLayout.addWidget(self.frames_per_buffer, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.apply = QtWidgets.QPushButton(SoundConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply.sizePolicy().hasHeightForWidth())
        self.apply.setSizePolicy(sizePolicy)
        self.apply.setObjectName("apply")
        self.verticalLayout.addWidget(self.apply, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(SoundConfig)
        QtCore.QMetaObject.connectSlotsByName(SoundConfig)

    def retranslateUi(self, SoundConfig):
        _translate = QtCore.QCoreApplication.translate
        SoundConfig.setWindowTitle(_translate("SoundConfig", "Form"))
        self.format.setItemText(0, _translate("SoundConfig", "1 Byte"))
        self.format.setItemText(1, _translate("SoundConfig", "2 Bytes"))
        self.format.setItemText(2, _translate("SoundConfig", "3 Bytes"))
        self.format.setItemText(3, _translate("SoundConfig", "4 Bytes"))
        self.label_4.setText(_translate("SoundConfig", "TASA DE MUESTREO"))
        self.label_3.setText(_translate("SoundConfig", "CANALES"))
        self.label.setText(_translate("SoundConfig", "FRAMES POR BUFFER"))
        self.label_2.setText(_translate("SoundConfig", "FORMATO"))
        self.sample_rate.setText(_translate("SoundConfig", "48000"))
        self.channels.setText(_translate("SoundConfig", "1"))
        self.frames_per_buffer.setText(_translate("SoundConfig", "1024"))
        self.apply.setText(_translate("SoundConfig", "Aplicar cambios"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SoundConfig = QtWidgets.QWidget()
    ui = Ui_SoundConfig()
    ui.setupUi(SoundConfig)
    SoundConfig.show()
    sys.exit(app.exec_())
